<?php

namespace Database\Seeders;

use App\Models\StructureType;
use Illuminate\Database\Seeder;

class StructureTypeSeeder extends Seeder
{
    /**
     * Initial structures. Each occupies a 20x20 footprint (generic units).
     *
     * Producers create resource per minute (up to a capacity ceiling).
     * The Warehouse is a storage structure: it produces nothing but protects
     * an amount of each resource, and its upgrade costs all three resources.
     *
     * Level scaling comes from *_base / *_growth (formula), editable in admin.
     * Formula: value(level) = round(base * growth^(level - 1)).
     */
    public function run(): void
    {
        $types = [
            [
                'key' => 'gold_mine',
                'name' => 'Mina de Ouro',
                'description' => 'Produz ouro a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'gold',
                'production_per_hour' => 100,
                'color' => '#f4c542',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Costs mostly gold, a little metal.
                'upgrade_cost_gold_base' => 200,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 40,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 0,
                'upgrade_cost_energy_growth' => 1.500,
                // Times in seconds.
                'build_time' => 30,
                'upgrade_time_base' => 60,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'metal_mine',
                'name' => 'Mina de Metal',
                'description' => 'Produz metal a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 100,
                'color' => '#9aa5b1',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'upgrade_cost_gold_base' => 60,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 160,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 0,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 30,
                'upgrade_time_base' => 60,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'power_plant',
                'name' => 'Gerador de Eletricidade',
                'description' => 'Produz eletricidade a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'energy',
                'production_per_hour' => 100,
                'color' => '#4fc3f7',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'upgrade_cost_gold_base' => 80,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 80,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 40,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 45,
                'upgrade_time_base' => 90,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'warehouse',
                'name' => 'Depósito',
                'description' => 'Protege uma quantidade de cada recurso de ser saqueada em ataques.',
                'category' => 'storage',
                'width' => 30,
                'height' => 40,
                'resource' => 'gold', // nominal; storage doesn't produce
                'production_per_hour' => 0,
                'color' => '#b07d4f',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                // Protects this much of EACH resource, growing per level.
                'protection_base' => 1000,
                'protection_growth' => 1.250,
                // Upgrade costs all three resources.
                'upgrade_cost_gold_base' => 150,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 150,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 150,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 60,
                'upgrade_time_base' => 120,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'command_center',
                'name' => 'Centro de Operações',
                'description' => 'Prédio principal da base. Aumenta o limite de construções e define o nível máximo das demais estruturas.',
                'category' => 'command',
                // 3x the size of the 20x20 resource structures.
                'width' => 60,
                'height' => 60,
                'resource' => 'gold', // nominal; command doesn't produce
                'production_per_hour' => 0,
                'color' => '#c9b037',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Only one Command Center per base.
                'is_unique' => true,
                // Grants +2 construction slots per level (linear: growth 0).
                'structure_slots_base' => 2,
                'structure_slots_growth' => 0,
                // Upgrade costs all three resources, more than the others.
                'upgrade_cost_gold_base' => 500,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 500,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 300,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 90,
                'upgrade_time_base' => 180,
                'upgrade_time_growth' => 1.400,
            ],

            // ---------------------------------------------------------------
            // PLANETARY (orbital) defense base. These live on scope=planetary.
            // Every planetary structure has HP (grows per level). Defense
            // structures also deal damage. Colors are shades of blue.
            // ---------------------------------------------------------------
            [
                'key' => 'defense_center',
                'name' => 'Centro de Defesa Planetária',
                'description' => 'Centro de operações da base planetária. Define o nível máximo das defesas e libera a quantidade de estruturas (considerado até o nível 15 para os limites de quantidade).',
                'category' => 'command',
                'scope' => 'planetary',
                // 3x the size of a defense unit (20x20).
                'width' => 60,
                'height' => 60,
                'resource' => 'gold', // nominal; command doesn't produce
                'production_per_hour' => 0,
                'color' => '#1e63d6',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Sturdy command structure.
                'hp_base' => 5000,
                'hp_growth' => 1.200,
                'damage_base' => 100,
                'damage_growth' => 1.200,
                // Only one Defense Center per base.
                'is_unique' => true,
                // Grants +2 construction slots per level (linear).
                'structure_slots_base' => 2,
                'structure_slots_growth' => 0,
                'upgrade_cost_gold_base' => 500,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 500,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 300,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 90,
                'upgrade_time_base' => 180,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'artillery',
                'name' => 'Artilharia',
                'description' => 'Defesa versátil que causa dano a invasores. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 0,
                'color' => '#3d8bff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 800,
                'hp_growth' => 1.200,
                'damage_base' => 120,
                'damage_growth' => 1.200,
                'upgrade_cost_gold_base' => 120,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 200,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 40,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 45,
                'upgrade_time_base' => 90,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'defense_block',
                'name' => 'Bloco de Defesa',
                'description' => 'Estrutura resistente que absorve dano protegendo as demais. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 0,
                'color' => '#2f6fd6',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // High HP, low damage: it's a wall.
                'hp_base' => 2500,
                'hp_growth' => 1.220,
                'damage_base' => 20,
                'damage_growth' => 1.150,
                'upgrade_cost_gold_base' => 80,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 260,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 20,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 40,
                'upgrade_time_base' => 80,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'plasma_cannon',
                'name' => 'Canhão de Plasma',
                'description' => 'Alto dano concentrado contra invasores. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'energy',
                'production_per_hour' => 0,
                'color' => '#5ab0ff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 700,
                'hp_growth' => 1.200,
                'damage_base' => 220,
                'damage_growth' => 1.220,
                'upgrade_cost_gold_base' => 100,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 120,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 200,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 60,
                'upgrade_time_base' => 120,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'cosmic_ray',
                'name' => 'Raio Cósmico',
                'description' => 'Superarma de dano devastador. Liberado 1 a cada 3 níveis do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                // Larger, imposing footprint.
                'width' => 30,
                'height' => 30,
                'resource' => 'energy',
                'production_per_hour' => 0,
                'color' => '#7fd0ff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 1500,
                'hp_growth' => 1.210,
                'damage_base' => 500,
                'damage_growth' => 1.250,
                'upgrade_cost_gold_base' => 300,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 300,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 500,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 120,
                'upgrade_time_base' => 240,
                'upgrade_time_growth' => 1.400,
            ],
        ];

        foreach ($types as $type) {
            StructureType::updateOrCreate(['key' => $type['key']], $type);
        }
    }
}
