<?php

namespace Database\Seeders;

use App\Models\StructureType;
use Illuminate\Database\Seeder;

class StructureTypeSeeder extends Seeder
{
    /**
     * Initial structures. Each occupies a 20x20 footprint (generic units).
     *
     * Producers create resource per minute (up to a capacity ceiling).
     * The Warehouse is a storage structure: it produces nothing but protects
     * an amount of each resource, and its upgrade costs all three resources.
     *
     * Level scaling comes from *_base / *_growth (formula), editable in admin.
     * Formula: value(level) = round(base * growth^(level - 1)).
     */
    public function run(): void
    {
        $types = [
            [
                'key' => 'gold_mine',
                'name' => 'Mina de Ouro',
                'description' => 'Produz ouro a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'gold',
                'production_per_hour' => 100,
                'color' => '#f4c542',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Costs mostly gold, a little metal.
                'upgrade_cost_gold_base' => 200,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 40,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 0,
                'upgrade_cost_energy_growth' => 1.500,
                // Times in seconds.
                'build_time' => 30,
                'upgrade_time_base' => 60,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'metal_mine',
                'name' => 'Mina de Metal',
                'description' => 'Produz metal a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 100,
                'color' => '#9aa5b1',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'upgrade_cost_gold_base' => 60,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 160,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 0,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 30,
                'upgrade_time_base' => 60,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'power_plant',
                'name' => 'Gerador de Eletricidade',
                'description' => 'Produz eletricidade a cada minuto.',
                'category' => 'producer',
                'width' => 20,
                'height' => 20,
                'resource' => 'energy',
                'production_per_hour' => 100,
                'color' => '#4fc3f7',
                'max_level' => 30,
                // TEMP (testes): produção linear +100/min por nível (growth 0 = linear).
                'production_base' => 100,
                'production_growth' => 0,
                // TEMP (testes): capacidade folgada para não cortar a produção.
                'capacity_base' => 1000000,
                'capacity_growth' => 0,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'upgrade_cost_gold_base' => 80,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 80,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 40,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 45,
                'upgrade_time_base' => 90,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'warehouse',
                'name' => 'Depósito',
                'description' => 'Protege uma quantidade de cada recurso de ser saqueada em ataques.',
                'category' => 'storage',
                'width' => 30,
                'height' => 40,
                'resource' => 'gold', // nominal; storage doesn't produce
                'production_per_hour' => 0,
                'color' => '#b07d4f',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                // Protects this much of EACH resource, growing per level.
                'protection_base' => 1000,
                'protection_growth' => 1.250,
                // Upgrade costs all three resources.
                'upgrade_cost_gold_base' => 150,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 150,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 150,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 60,
                'upgrade_time_base' => 120,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'command_center',
                'name' => 'Centro de Operações',
                'description' => 'Prédio principal da base. Aumenta o limite de construções e define o nível máximo das demais estruturas.',
                'category' => 'command',
                // 3x the size of the 20x20 resource structures.
                'width' => 60,
                'height' => 60,
                'resource' => 'gold', // nominal; command doesn't produce
                'production_per_hour' => 0,
                'color' => '#c9b037',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Only one Command Center per base.
                'is_unique' => true,
                // Grants +2 construction slots per level (linear: growth 0).
                'structure_slots_base' => 2,
                'structure_slots_growth' => 0,
                // Upgrade costs all three resources, more than the others.
                'upgrade_cost_gold_base' => 500,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 500,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 300,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 90,
                'upgrade_time_base' => 180,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'aircraft_hangar',
                'name' => 'Hangar de Aeronaves',
                'description' => 'Constrói e abriga aeronaves. Cada nível reduz o tempo de construção das aeronaves. Segue os mesmos requisitos das demais construções da base (limitado pelo nível do Centro de Operações).',
                'category' => 'support',
                'scope' => 'terrestrial',
                // Large footprint requested: 50x80.
                'width' => 50,
                'height' => 80,
                'resource' => 'metal', // nominal; support doesn't produce
                'production_per_hour' => 0,
                'color' => '#8e7cc3',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Reduces aircraft build time by +2% per level (linear, growth 0):
                // level 1 = 2%, level 30 = 60%. Clamped at 90% by the calculator.
                'build_time_reduction_base' => 2,
                'build_time_reduction_growth' => 0,
                // Fleet governance. Build slots use configurable level tiers
                // (JSON): 1 slot up to L8, 2 up to L16, 3 up to L24, 5 at L30.
                // The base/growth below is the fallback if tiers are cleared.
                'build_slots_base' => 1,
                'build_slots_growth' => 0,
                'build_slots_tiers' => [
                    ['upTo' => 8, 'slots' => 1],
                    ['upTo' => 16, 'slots' => 2],
                    ['upTo' => 24, 'slots' => 3],
                    ['upTo' => 30, 'slots' => 5],
                ],
                // fleet capacity: +5 aircraft per level (level 1 = 5, level 30 = 150).
                'fleet_capacity_base' => 5,
                'fleet_capacity_growth' => 0,
                // Only one Aircraft Hangar per base.
                'is_unique' => true,
                // Costs all three resources; heavier on metal/energy.
                'upgrade_cost_gold_base' => 200,
                'upgrade_cost_gold_growth' => 1.550,
                'upgrade_cost_metal_base' => 400,
                'upgrade_cost_metal_growth' => 1.550,
                'upgrade_cost_energy_base' => 300,
                'upgrade_cost_energy_growth' => 1.550,
                'build_time' => 120,
                'upgrade_time_base' => 200,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'protector_fort',
                'name' => 'Forte Protetor',
                'description' => 'Caixa de itens do dono do planeta. Guarda os itens (consumíveis e plantas) do jogador. Começa com 30 espaços e ganha +2 por nível. Segue os mesmos requisitos das demais construções da base (limitado pelo nível do Centro de Operações).',
                'category' => 'inventory',
                'scope' => 'terrestrial',
                // Footprint requested: 35x50.
                'width' => 35,
                'height' => 50,
                'resource' => 'gold', // nominal; inventory doesn't produce
                'production_per_hour' => 0,
                'color' => '#4caf7d',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Item slots: 30 at level 1, +2 per level (88 at level 30).
                'inventory_slots_base' => 30,
                'inventory_slots_per_level' => 2,
                // Only one Forte Protetor per base.
                'is_unique' => true,
                // Costs all three resources.
                'upgrade_cost_gold_base' => 200,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 300,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 150,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 90,
                'upgrade_time_base' => 180,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'research_center',
                'name' => 'Centro de Pesquisa',
                'description' => 'Libera o painel de pesquisas (tecnologias e plantas). Cada nível reduz o tempo de pesquisa (até 60% no máximo). Só é possível pesquisar uma coisa por vez. Segue os mesmos requisitos das demais construções da base (limitado pelo nível do Centro de Operações).',
                'category' => 'research',
                'scope' => 'terrestrial',
                // Footprint requested: 100x30.
                'width' => 100,
                'height' => 30,
                'resource' => 'gold', // nominal; research doesn't produce
                'production_per_hour' => 0,
                'color' => '#7ec8e3',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Research time reduction: 0% at level 1, +3%/level, capped 60%
                // (reaches the 60% ceiling at level 21).
                'research_time_reduction_base' => 0,
                'research_time_reduction_per_level' => 3,
                'research_time_reduction_cap' => 60,
                // Only one Centro de Pesquisa per base.
                'is_unique' => true,
                // Costs all three resources.
                'upgrade_cost_gold_base' => 300,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 400,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 250,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 120,
                'upgrade_time_base' => 240,
                'upgrade_time_growth' => 1.400,
            ],

            // ---------------------------------------------------------------
            // PLANETARY (orbital) defense base. These live on scope=planetary.
            // Every planetary structure has HP (grows per level). Defense
            // structures also deal damage. Colors are shades of blue.
            // ---------------------------------------------------------------
            [
                'key' => 'defense_center',
                'name' => 'Centro de Defesa Planetária',
                'description' => 'Centro de operações da base planetária. Define o nível máximo das defesas e libera a quantidade de estruturas (considerado até o nível 15 para os limites de quantidade).',
                'category' => 'command',
                'scope' => 'planetary',
                // 3x the size of a defense unit (20x20).
                'width' => 60,
                'height' => 60,
                'resource' => 'gold', // nominal; command doesn't produce
                'production_per_hour' => 0,
                'color' => '#1e63d6',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // Sturdy command structure.
                'hp_base' => 5000,
                'hp_growth' => 1.200,
                'damage_base' => 100,
                'damage_growth' => 1.200,
                'range_base' => 5,
                'range_growth' => 1.050,
                // Only one Defense Center per base.
                'is_unique' => true,
                // Grants +2 construction slots per level (linear).
                'structure_slots_base' => 2,
                'structure_slots_growth' => 0,
                'upgrade_cost_gold_base' => 500,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 500,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 300,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 90,
                'upgrade_time_base' => 180,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'artillery',
                'name' => 'Artilharia',
                'description' => 'Defesa versátil que causa dano a invasores. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 0,
                'color' => '#3d8bff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 800,
                'hp_growth' => 1.200,
                'damage_base' => 120,
                'damage_growth' => 1.200,
                // Balanced reach (in cells). Grows slowly with level.
                'range_base' => 4,
                'range_growth' => 1.050,
                'upgrade_cost_gold_base' => 120,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 200,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 40,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 45,
                'upgrade_time_base' => 90,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'defense_block',
                'name' => 'Bloco de Defesa',
                'description' => 'Estrutura resistente que absorve dano protegendo as demais. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'metal',
                'production_per_hour' => 0,
                'color' => '#2f6fd6',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                // High HP, low damage: it's a wall.
                'hp_base' => 2500,
                'hp_growth' => 1.220,
                'damage_base' => 20,
                'damage_growth' => 1.150,
                // Very short reach: it only hits what's right next to it.
                'range_base' => 1,
                'range_growth' => 1.000,
                'upgrade_cost_gold_base' => 80,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 260,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 20,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 40,
                'upgrade_time_base' => 80,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'plasma_cannon',
                'name' => 'Canhão de Plasma',
                'description' => 'Alto dano concentrado contra invasores. Limite: 3 por nível do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                'width' => 20,
                'height' => 20,
                'resource' => 'energy',
                'production_per_hour' => 0,
                'color' => '#5ab0ff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 700,
                'hp_growth' => 1.200,
                'damage_base' => 220,
                'damage_growth' => 1.220,
                // Medium reach for concentrated fire.
                'range_base' => 3,
                'range_growth' => 1.050,
                'upgrade_cost_gold_base' => 100,
                'upgrade_cost_gold_growth' => 1.500,
                'upgrade_cost_metal_base' => 120,
                'upgrade_cost_metal_growth' => 1.500,
                'upgrade_cost_energy_base' => 200,
                'upgrade_cost_energy_growth' => 1.500,
                'build_time' => 60,
                'upgrade_time_base' => 120,
                'upgrade_time_growth' => 1.400,
            ],
            [
                'key' => 'cosmic_ray',
                'name' => 'Raio Cósmico',
                'description' => 'Superarma de dano devastador. Liberado 1 a cada 3 níveis do Centro de Defesa.',
                'category' => 'defense',
                'scope' => 'planetary',
                // Larger, imposing footprint.
                'width' => 30,
                'height' => 30,
                'resource' => 'energy',
                'production_per_hour' => 0,
                'color' => '#7fd0ff',
                'max_level' => 30,
                'production_base' => 0,
                'production_growth' => 1.000,
                'capacity_base' => 0,
                'capacity_growth' => 1.000,
                'protection_base' => 0,
                'protection_growth' => 1.000,
                'hp_base' => 1500,
                'hp_growth' => 1.210,
                'damage_base' => 500,
                'damage_growth' => 1.250,
                // Long reach: it's a devastating superweapon.
                'range_base' => 6,
                'range_growth' => 1.060,
                'upgrade_cost_gold_base' => 300,
                'upgrade_cost_gold_growth' => 1.600,
                'upgrade_cost_metal_base' => 300,
                'upgrade_cost_metal_growth' => 1.600,
                'upgrade_cost_energy_base' => 500,
                'upgrade_cost_energy_growth' => 1.600,
                'build_time' => 120,
                'upgrade_time_base' => 240,
                'upgrade_time_growth' => 1.400,
            ],
        ];

        foreach ($types as $type) {
            StructureType::updateOrCreate(['key' => $type['key']], $type);
        }
    }
}
